# Generated by Django 2.2.4 on 2019-08-19 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlparsetimeshift',
            name='time_dalay_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlparsetimeshift',
            name='time_dalay_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 13, 45, 51, 288354), verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
    ]
