# Generated by Django 2.2.4 on 2019-08-19 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0002_auto_20190819_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlparsetimeshift',
            old_name='time_dalay_minutes',
            new_name='time_delay_minutes',
        ),
        migrations.RenameField(
            model_name='urlparsetimeshift',
            old_name='time_dalay_seconds',
            new_name='time_delay_seconds',
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 13, 59, 22, 191735), verbose_name='Start time'),
        ),
    ]
