# Generated by Django 2.2.4 on 2019-08-19 06:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0003_auto_20190819_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlparsetimeshift',
            name='status_executed',
            field=models.BooleanField(default=False, verbose_name='Executed'),
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 19, 14, 42, 19, 187131), verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='time_delay_minutes',
            field=models.IntegerField(default=0, help_text='>0', validators=[django.core.validators.MinValueValidator(0, 'value < 0')]),
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='time_delay_seconds',
            field=models.IntegerField(default=0, help_text='0-59', validators=[django.core.validators.MinValueValidator(0, 'value < 0'), django.core.validators.MaxValueValidator(59, 'value > 59')]),
        ),
    ]
