# Generated by Django 2.2.4 on 2019-08-20 03:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0005_auto_20190820_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 3, 11, 21, 983435, tzinfo=utc), verbose_name='Start time'),
        ),
    ]
