# Generated by Django 2.2.4 on 2019-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0007_auto_20190820_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='response_code',
            field=models.IntegerField(default=None),
        ),
    ]
