# Generated by Django 2.2.4 on 2019-08-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteparser', '0008_auto_20190820_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlparsetimeshift',
            name='response_charset',
            field=models.CharField(default='', max_length=20, verbose_name='charset'),
        ),
        migrations.AddField(
            model_name='urlparsetimeshift',
            name='response_h1',
            field=models.CharField(default='', max_length=500, verbose_name='h1'),
        ),
        migrations.AddField(
            model_name='urlparsetimeshift',
            name='response_title',
            field=models.CharField(default='', max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='urlparsetimeshift',
            name='response_code',
            field=models.IntegerField(default=0),
        ),
    ]
